version: "3"
services:
  application:
    image: spring-boot-mongodb-app
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mongodb
    volumes:
      - /data/springboot-app

  mongodb:
    image: mongo:latest
    networks:
      - springboot-db-net
    volumes:
      - mongodb-data:/data/db

networks:
  springboot-db-net:
